#!/usr/bin/env python
"""Generate placeholder definitions for every result macro the paper cites.

The manuscript quotes measured values through macros that the evaluation
notebook writes. Before the experiments have run those macros do not exist and
the document will not compile, which makes it impossible to draft the prose and
the experiments in parallel.

This scans the LaTeX sources for `\\Res...` commands and emits a
`\\providecommand` for each, rendering as a conspicuous red marker. Because
`\\providecommand` defines only what is missing, the real values always win --
provided `fallbacks.tex` is loaded *after* `results_macros.tex`.

    python scripts/make_fallbacks.py [--paper ../] [--check]

`--check` exits non-zero if any macro is still unresolved, which is the
pre-submission gate: a PDF containing [PENDING] must never be uploaded.
"""

from __future__ import annotations

import argparse
import os
import re
from typing import List, Set

MACRO_PATTERN = re.compile(r"\\(Res[A-Za-z]+)")
DEFINITION_PATTERN = re.compile(r"\\newcommand\{\\(Res[A-Za-z]+)\}")


def find_tex_sources(paper_dir: str) -> List[str]:
    sources = []
    for name in sorted(os.listdir(paper_dir)):
        if name.endswith(".tex"):
            sources.append(os.path.join(paper_dir, name))
    tables = os.path.join(paper_dir, "tables")
    if os.path.isdir(tables):
        for name in sorted(os.listdir(tables)):
            if name.endswith(".tex") and name not in {"fallbacks.tex", "results_macros.tex"}:
                sources.append(os.path.join(tables, name))
    return sources


def collect_used(sources: List[str]) -> Set[str]:
    used: Set[str] = set()
    for path in sources:
        with open(path, encoding="utf-8") as f:
            used.update(MACRO_PATTERN.findall(f.read()))
    return used


def collect_defined(macros_path: str) -> Set[str]:
    if not os.path.exists(macros_path):
        return set()
    with open(macros_path, encoding="utf-8") as f:
        return set(DEFINITION_PATTERN.findall(f.read()))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--paper", default=None,
                        help="directory containing main.tex (default: repository parent)")
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if any cited macro has no measured value")
    args = parser.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    paper_dir = os.path.abspath(args.paper or os.path.dirname(repo_root))
    tables_dir = os.path.join(paper_dir, "tables")
    os.makedirs(tables_dir, exist_ok=True)

    sources = find_tex_sources(paper_dir)
    if not sources:
        print(f"no .tex sources found in {paper_dir}")
        return 1

    used = collect_used(sources)
    defined = collect_defined(os.path.join(tables_dir, "results_macros.tex"))
    missing = sorted(used - defined)

    print(f"paper: {paper_dir}")
    print(f"  {len(sources)} source file(s), {len(used)} result macros cited, "
          f"{len(defined)} measured")

    if args.check:
        if missing:
            print(f"\nUNRESOLVED ({len(missing)}): these would print as [PENDING] in the PDF")
            for name in missing:
                print("  -", name)
            print("\nRun the evaluation notebook, copy its tables/ output here, and re-check.")
            return 1
        print("\nall cited macros have measured values -- safe to submit")
        return 0

    out = os.path.join(tables_dir, "fallbacks.tex")
    lines = [
        "% Auto-generated by scripts/make_fallbacks.py -- do not edit by hand.",
        "%",
        "% \\providecommand, not \\newcommand: these define only the macros that",
        "% tables/results_macros.tex has not already supplied. Load this file AFTER",
        "% results_macros.tex so measured values always take precedence.",
        "%",
        "% Anything rendering as a red [PENDING] is a number the experiments have",
        "% not produced yet. scripts/make_fallbacks.py --check fails while any remain.",
        "",
        "\\providecommand{\\ResPending}{\\textcolor{red}{\\textbf{[PENDING]}}}",
        "",
    ]
    for name in sorted(used):
        lines.append(f"\\providecommand{{\\{name}}}{{\\ResPending}}")
    lines.append("")

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"  wrote {out}")
    if missing:
        print(f"  {len(missing)} macro(s) still awaiting measured values:")
        for name in missing[:12]:
            print("     -", name)
        if len(missing) > 12:
            print(f"     ... and {len(missing) - 12} more")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
